config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :show]
  resources :companies, only: [:index, :show]

  # Routes for users
  resources :users, only: [:new, :create]

  # Routes for sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'session', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  ##Associations
  has_many :involved_companies
  has_many :games, through: :involved_companies
  has_many :reviews, as: :reviewable

  ##Validations
  validates :name, :country, presence: true
  validates :name, uniqueness: true
end

app/models/game.rb
class Game < ApplicationRecord
  ##Associations
  has_many :involved_companies
  has_many :companies, through: :involved_companies
  has_and_belongs_to_many :platforms
  has_and_belongs_to_many :genres
  has_many :expansions, class_name: "Game", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Game", optional: true
  has_many :reviews, as: :reviewable

  ##Validations
  validates :name, :category, presence: true
  validates :name, uniqueness: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validate :valid_game_id_when_expansion_category

  ##Enum
  enum category: {main_game: 0, expansion: 1}

  ##Custom Validations
  private
  def valid_game_id_when_expansion_category
    if category=="expansion" && parent.nil?
      errors.add(:game_id, "parent game not exist for current expansion game")
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  ##Associations
  has_and_belongs_to_many :games

  ##Validations
  validates :name, presence: true, uniqueness: true
end

app/models/involved_company.rb
class InvolvedCompany < ApplicationRecord
  ##Association
  belongs_to :company
  belongs_to :game

  ##Validation
  validates :developer, :publisher, inclusion: [true, false]
end

app/models/platform.rb
class Platform < ApplicationRecord
  ##Associations
  has_and_belongs_to_many :games

  ##Validations
  validates :name, :category, presence: true
  validates :name, uniqueness: true

  #Enum
  enum category: 
  {
    console: 0,
    arcade: 1,
    platform: 2,
    operating_system: 3,
    portable_console: 4,
    computer: 5
  }
end

app/models/review.rb
class Review < ApplicationRecord
  ##Associations
  belongs_to :user
  belongs_to :reviewable, polymorphic: true

  ##Validations
  validates :title, :body, presence: true
  validates :title, length: { maximum: 40 }, uniqueness: true

  ##Callback
  after_create Proc.new{|review| up_review_count_of_user_owner(review)}
  after_destroy Proc.new{|review| down_review_count_of_user_owner(review)}

  private
  def up_review_count_of_user_owner(review)
    user = review.user
    user.review_count +=1
    user.save
  end

  private
  def down_review_count_of_user_owner(review)
    user = review.user
    user.review_count -=1
    user.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  require 'time_difference'
  ##Associations
  has_many :reviews

  ##Validations
  validates :username, :email, presence: true, uniqueness: true
  validate :valid_birth_date

  ##use bcrypt (columna password_digest required)
  has_secure_password

  ##Custom Validations
  private
  def valid_birth_date
    if birth_date.present? && TimeDifference.between(birth_date, DateTime.now).in_years < 16
      errors.add(:birth_date, "You should be 16 years old to create an account")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "welcome"
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def welcome
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/games'
    else
      redirect_to '/login', notice: "Username or password invalid"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/welcome'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "welcome"
  skip_before_action :authorized, only: [:new,:create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/games'
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :birth_date, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/index.html.erb
<h1>All companies</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <% for company in @companies %>
    <tr>
      <td><%= company.name %></td>
      <td><%= link_to "Show", company_path(company) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>
<p><%= @company.description%></p>
<ul>
  <li>Country: <%= @company.country %></li>
  <li>Start Date: <%= @company.start_date %></li>
</ul>

app/views/games/index.html.erb
<h1>All games</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <% for game in @games %>
    <tr>
      <td><%= game.name %></td>
      <td><%= game.rating %></td>
      <td><%= link_to "Show", game_path(game) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/games/show.html.erb
<h1><%= @game.name %></h1>
<p><%= @game.summary%></p>
<ul>
  <li>Rating: <%= @game.rating %></li>
  <li>Release Date: <%= @game.release_date %></li>
  <li>Platform(s): <%= @game.platforms.map{|platform| platform.name}.join(", ") %></li>
  <li>Genre(s): <%= @game.genres.map{|genre| genre.name}.join(", ") %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CriticxAlpha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CriticxAlphaViews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= notice %></p>
    <p><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>

<%= form_for @user do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.label :birth_date%><br>
  <%= f.text_field :birth_date%><br>
  <%= f.label :email%><br>
  <%= f.text_field :email%><br>
  <%= f.submit %>
<%end%>